# Generated by Django 5.0.2 on 2024-04-18 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("art", "0004_alter_categories_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="art",
            old_name="catogories",
            new_name="categories",
        ),
    ]
