# Generated by Django 5.0.2 on 2024-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art", "0005_rename_catogories_art_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="image2",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=""),
        ),
    ]
