# Generated by Django 5.0.2 on 2024-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art", "0006_alter_art_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="art",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
