# Generated by Django 5.0.2 on 2024-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_date_joined_user_groups_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=11, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="password"),
        ),
    ]
